# Generated by Django 4.1.3 on 2023-07-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jazzyburger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
